# Generated by Django 4.2.7 on 2023-11-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, unique=True, verbose_name='катигория расходов')),
            ],
            options={
                'verbose_name': 'катигория',
                'verbose_name_plural': 'катигории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='имя')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='пароль')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.IntegerField(default=0, verbose_name='даход')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_id', to='consumption.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'даход',
                'verbose_name_plural': 'даходы',
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.IntegerField(default=0, verbose_name='сумма расхода')),
                ('data', models.DateField(verbose_name='дата')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_id', to='consumption.category', verbose_name='катигория')),
            ],
            options={
                'verbose_name': 'расход',
                'verbose_name_plural': 'расходы',
                'db_table': 'consumption',
            },
        ),
    ]
