# Generated by Django 4.2.7 on 2023-11-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumption', '0003_remove_users_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_category', models.CharField(max_length=100, verbose_name='Категории пользователя')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'катигория ',
                'verbose_name_plural': 'катигории',
                'db_table': 'user_category',
            },
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
