# Generated by Django 4.2.7 on 2023-11-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_usercategory_remove_consumption_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'катигория ', 'verbose_name_plural': 'выбранные катигории'},
        ),
    ]
